server:
  port: 8082

spring:
  application:
    name: unipush-webhook
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:unipush-webhook.yml?namespace=unipush&group=DEFAULT_GROUP
  cloud:
    nacos:
      config:
        server-addr: 192.168.31.88:8848
        namespace: unipush
        file-extension: yml

  # Kafka配置
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: unipush-webhook-group
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 10
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

# WebClient配置
spring.webclient:
  connect-timeout: 5000
  read-timeout: 10000

# 日志配置
logging:
  level:
    top.zhengru.unipush: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
